export const FETCHED_ALL_STUDENTS = "students.FETCHED_ALL_STUDENTS";
export const ERROR_FETCHING_STUDENTS = "students.ERROR_FETCHING_STUDENTS";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_ERROR = "CREATE_STUDENT_ERROR";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";
